# Basic Information 
project: Seriscope: A low cost edge-AI system for fertility and disease assessment of Tassar silkworm eggs
title: Suryakanta Lenka & Tripathy Divyajyoti Senapati
position: Grade X & Grade XI
affiliation: DAV Public School, Unit-VIII
email: seriscope (at) tdivyajyotis.in

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: seriscope sericulture microscopy
description: A low cost edge-AI system for fertility and disease assessment of Tassar silkworm eggs
canonical: https://seriscope.tdivyajyotis.in/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/logo.jpg
favicon: ./assets/favicon-32x32.png
favicon_dark: ./assets/favicon-32x32.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
